global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:8084']

  - job_name: 'content-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['content-service:8082']

